services:
  - type: web
    name: juno-ui
    env: static
    buildCommand: npm install && npm run build:site
    staticPublishPath: ./site-dist
    pullRequestPreviewsEnabled: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: juno-ui-storybook
    env: static
    buildCommand: npm install && npm run build-storybook
    staticPublishPath: ./storybook-static
    pullRequestPreviewsEnabled: true
